packages:
  - '.'
  - 'packages/*'

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true

pnpm:
  allowBuilds:
    "@firebase/util": true
    "@parcel/watcher": true
    "@swc/core": true
    "esbuild": true
    "lmdb": true
    "msgpackr-extract": true
    "protobufjs": true
    "sharp": true
